version: '3.6'

services:
  nginx:
    image: nginx:1.13.1
    restart: always
    container_name: nginx-proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs

  dockergen:
#    image: jwilder/docker-gen:0.7.3
    image: helder/docker-gen:latest
#    image: kdzch/docker-gen-swarm
    restart: always
    container_name: nginx-proxy-gen
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen:
    deploy:
      placement:
        constraints:
          - node.role == manager
    depends_on:
      - nginx

#    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    command: -notify "docker-label-sighup com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy" -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    container_name: nginx-proxy-le
    depends_on:
      - nginx
      - dockergen
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro

  ssh-proxy:
    image: mickaelperrin/docker-ssh-proxy
    container_name: ssh-proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    restart: always
    ports:
      - 2222:2222
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  conf:
  vhost:
  html:
  certs:

networks:
  default:
    external:
      name: nginx-proxy
